[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"
  STRIPE_SECRET_KEY = "sk_test_placeholder"
  STRIPE_WEBHOOK_SECRET = "whsec_placeholder"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"
  OPENAI_API_KEY = "dummy-key"

[functions]
  directory = ".next/serverless"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
