[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-audit --no-fund"
  STRIPE_SECRET_KEY = "sk_test_placeholder"
  STRIPE_WEBHOOK_SECRET = "whsec_placeholder"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_placeholder"
  OPENAI_API_KEY = "dummy-key"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/**/*"]
  node_bundler = "esbuild"
