export const DEFAULT_CLOSING_COST_PERCENT = 1.67;

export const EXPENSE_GROWTH = {
  PROPERTY_TAX: 0.02,
  INSURANCE: 0.01,
  UTILITIES: 0.03,
};

export const MIN_VALUES = {
  PURCHASE_PRICE: 1000,
  MONTHLY_RENT: 1,
  INTEREST_RATE: 0.01,
  DOWN_PAYMENT_PERCENT: 0,
  LOAN_TERM_YEARS: 1,
};
